name: Test runner

on:
  push:
    branches:
      - master

jobs:
  run-tests:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
        jdk: [8, 11, 17, 21, 24]

    name: Test on ${{ matrix.os }} with JDK ${{ matrix.jdk }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.jdk }}
          java-package: jdk
      - uses: DeLaGuardo/setup-clojure@12.5
        with:
          lein: 2.9.1
      - run: lein test-all
