name: Test runner

on:
  push:
    branches:
      - master

jobs:
  run-tests:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        jdk: [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]

    name: Test on ${{ matrix.os }} with JDK ${{ matrix.jdk }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.jdk }}
          java-package: jdk
      - run: lein test-all
